---

- hosts: all
  become: true
  tasks:

  - name: install apache2 and php
    tags: always
    package:
      name:
        - "{{ apache_package }}"
        - "{{ php_package }}"
      update_cache: yes
      state: latest

  - name: copy default html file for site
    tags: apache,apache2,httpd
    copy:
     src: default_site.html
     dest: /var/www/html/index.html
     owner: root
     group: root
     mode: 0644
