---

- hosts: all
  become: true
  tasks:

  - name: install apache2 and php
    tags: always
    package:
      name:
        - "{{ apache_package }}"
        - "{{ php_package }}"
      update_cache: yes
      state: latest

  - name: copy default html file for site
    tags: apache,apache2,httpd
    copy:
     src: default_site.html
     dest: /var/www/html/index.html
     owner: root
     group: root
     mode: 0644

- hosts: workstations
  become: true
  tasks:

  - name: install unzip
    package:
      name: unzip

  - name: download terraform
    get_url:
      url: https://releases.hashicorp.com/terraform/1.11.4/terraform_1.11.4_linux_amd64.zip
      dest: /tmp/terraform.zip
      mode: 0644

  - name: extract terraform
    unarchive:
      src: /tmp/terraform.zip
      dest: /usr/local/bin
      remote_src: yes
      mode: 0755
      owner: root
      group: root
